import os
import json
import logging
import asyncio
from typing import Literal, Optional, List, Dict, Any

from core.database import db_cursor
from core.ai import resolve_provider, chat_completion, AIProviderUnavailable
from core.security import generate_id
from services.workspaces import require_ws_access
from services.safety_review import classify_safety
from services.audit_proposals import create_proposal
from services.notifications import send_consult_notification

logger = logging.getLogger(__name__)

async def get_active_providers(user_id: str) -> List[str]:
    """Get list of active provider names for the user or system fallback."""
    with db_cursor() as cur:
        cur.execute(
            "SELECT provider FROM user_ai_keys WHERE user_id = %s OR user_id = 'system'",
            (user_id,)
        )
        return [row["provider"] for row in cur.fetchall()]

async def run_single_consult(
    resolved_prov,
    system_prompt: str,
    user_msg: str,
    max_tokens: int = 1024,
    temperature: float = 0.2
) -> tuple[str, int]:
    try:
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_msg}
        ]
        return await chat_completion(
            resolved=resolved_prov,
            messages=messages,
            max_tokens=max_tokens,
            temperature=temperature
        )
    except Exception as e:
        logger.error(f"Error during AI consult chat completion: {e}")
        raise

async def synthesize_responses(
    ws_id: str,
    user_id: str,
    responses: List[str]
) -> tuple[str, str]:
    """
    Synthesize N responses. Returns (synthesis_result, reasoning).
    synthesis_result is 'consensus' or 'divergent'.
    """
    if len(responses) <= 1:
        return "consensus", "Single model consultation. No fanning out needed."
        
    try:
        resolved = resolve_provider(user_id=user_id, feature="chat")
    except AIProviderUnavailable:
        # Fallback to simple text checking or default to consensus
        return "consensus", "Synthesizer provider unavailable. Defaulted to consensus."
        
    system_prompt = (
        "You are an expert consensus analyzer. Compare the following troubleshooting proposals generated by different AI models. "
        "Determine if they are in agreement (consensus) or if they diverge/contradict each other (divergent). "
        "Agreeing means they suggest similar logical steps or commands to troubleshoot the problem. "
        "Diverging means they suggest completely contradictory or unrelated paths.\n"
        "Respond ONLY in valid JSON format: {\"synthesis_result\": \"consensus\" | \"divergent\", \"reasoning\": \"...\"}"
    )
    
    user_msg = "Proposals to compare:\n\n"
    for idx, resp in enumerate(responses):
        user_msg += f"--- Proposal {idx+1} ---\n{resp}\n\n"
        
    try:
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_msg}
        ]
        res_text, _ = await chat_completion(
            resolved=resolved,
            messages=messages,
            max_tokens=512,
            temperature=0.1
        )
        # Clean markdown wrappers if any
        import re
        cleaned = re.sub(r"```json|```", "", res_text).strip()
        data = json.loads(cleaned)
        return data.get("synthesis_result", "consensus"), data.get("reasoning", " consensus by default")
    except Exception as e:
        logger.error(f"Error in synthesizer: {e}")
        return "consensus", f"Synthesizer error: {e}"

async def consult(
    ws_id: str,
    stuck_node_id: str,
    problem_context: str,
    mode: Literal['interpret', 'generate'],
    user: dict,
    inquiry_path_id: Optional[str] = None
) -> dict:
    user_id = user.get("sub", "system")
    
    with db_cursor(commit=True) as cur:
        # 1. Access Check
        workspace = require_ws_access(cur, ws_id, user, write=False)
        settings = workspace.get("settings") or {}
        if isinstance(settings, str):
            settings = json.loads(settings)
            
        # 2. Budget Gate Check
        cur.execute(
            """
            SELECT COUNT(*) AS count 
            FROM consult_sessions 
            WHERE workspace_id = %s 
              AND created_at >= date_trunc('day', now() AT TIME ZONE 'UTC')
            """,
            (ws_id,)
        )
        session_count = cur.fetchone()["count"]
        quota = settings.get("consult_daily_quota", 10)
        
        # Stuck Node Details
        cur.execute(
            "SELECT id, title, body, tags, content_type FROM memory_nodes WHERE id = %s AND workspace_id = %s",
            (stuck_node_id, ws_id)
        )
        stuck_node = cur.fetchone()
        if not stuck_node:
            raise ValueError(f"Stuck node {stuck_node_id} not found in workspace {ws_id}")
            
        if session_count >= quota:
            logger.warning(f"Consult daily quota ({quota}) exceeded for workspace {ws_id}. Downgrading to gap node.")
            # Downgrade: Create a gap node if not exists
            cur.execute(
                """
                SELECT id FROM memory_nodes 
                WHERE workspace_id = %s 
                  AND content_type = 'gap' 
                  AND title = %s 
                  AND status = 'active'
                """,
                (ws_id, f"Gap at {stuck_node['title']}")
            )
            if not cur.fetchone():
                from services.nodes import create_node_in_db
                gap_payload = {
                    "title": f"Gap at {stuck_node['title']}",
                    "content_type": "gap",
                    "content_format": "plain",
                    "body": f"Consult requested on node '{stuck_node['title']}' but quota exceeded. Context: {problem_context}",
                    "tags": ["quota_exceeded", "consult_gap"],
                    "visibility": "private",
                    "author": user_id,
                    "status": "active"
                }
                create_node_in_db(cur, ws_id, gap_payload)
            
            # Save session
            session_id = generate_id("con")
            cur.execute(
                """
                INSERT INTO consult_sessions (id, workspace_id, stuck_node_id, problem_context, mode, synthesis_result, inquiry_path_id)
                VALUES (%s, %s, %s, %s, %s, 'budget_limit', %s)
                """,
                (session_id, ws_id, stuck_node_id, problem_context, mode, inquiry_path_id)
            )
            return {
                "status": "budget_exceeded",
                "message": f"Daily consult quota of {quota} exceeded. A gap node has been registered.",
                "session_id": session_id
            }

    # Fetch provider key
    try:
        preferred_provider = workspace.get("consult_provider")
        resolved = resolve_provider(user_id=user_id, feature="chat", preferred_provider=preferred_provider)
    except AIProviderUnavailable:
        # Fallback to system:safety
        try:
            resolved = resolve_provider(user_id="system:safety", feature="chat")
        except AIProviderUnavailable:
            return {"status": "error", "message": "No AI provider keys configured for consultation."}

    # Retrieve context nodes for interpret mode
    candidate_nodes = []
    if mode == "interpret":
        with db_cursor() as cur:
            cur.execute(
                "SELECT id, title, content_type, body FROM memory_nodes WHERE workspace_id = %s AND status = 'active' LIMIT 50",
                (ws_id,)
            )
            candidate_nodes = [dict(r) for r in cur.fetchall()]

    # 3. Model Request Generation
    if mode == "interpret":
        system_prompt = (
            "You are a professional troubleshooting consultant. Your goal is to interpret the tool output that caused the agent "
            "to get stuck at the current node, and suggest which EXISTING nodes (by title/ID) or edges in the workspace the agent should traverse next to continue troubleshooting.\n"
            "Respond ONLY in valid JSON format: {\"action\": \"recommend_existing\", \"node_ids\": [\"node_id_1\", ...], \"reason\": \"...\"}"
        )
        user_msg = (
            f"Stuck Node Title: {stuck_node['title']}\n"
            f"Stuck Node Body: {stuck_node['body']}\n"
            f"Stuck Node Tags: {stuck_node['tags']}\n"
            f"Problem Context (Tool Output / Error): {problem_context}\n\n"
            f"Available candidate nodes in workspace:\n"
            + "\n".join([f"- ID: {n['id']}, Title: {n['title']}, Type: {n['content_type']}" for n in candidate_nodes])
        )
        
        res_text, _ = await run_single_consult(resolved, system_prompt, user_msg)
        # Clean response
        import re
        res_text = re.sub(r"```json|```", "", res_text).strip()
        result_data = json.loads(res_text)
        
        session_id = generate_id("con")
        with db_cursor(commit=True) as cur:
            cur.execute(
                """
                INSERT INTO consult_sessions (id, workspace_id, stuck_node_id, problem_context, mode, synthesis_result, inquiry_path_id, metadata)
                VALUES (%s, %s, %s, %s, %s, 'consensus', %s, %s)
                """,
                (session_id, ws_id, stuck_node_id, problem_context, mode, inquiry_path_id, json.dumps(result_data))
            )
        return {
            "status": "success",
            "mode": mode,
            "session_id": session_id,
            "suggestion": result_data
        }

    else:  # mode == 'generate'
        system_prompt = (
            "You are an expert troubleshooter. When the troubleshooting graph does not have any node matching the current problem context, "
            "your job is to generate a new procedural troubleshooting node. The node must contain practical steps (commands, checks, etc.) "
            "to resolve or diagnose the issue. You must also suggest an edge connecting the stuck node to this new node.\n"
            "Respond ONLY in valid JSON format: {\n"
            "  \"action\": \"create_node_and_edge\",\n"
            "  \"new_node\": {\n"
            "    \"title\": \"Clear descriptive title of the next step\",\n"
            "    \"content_type\": \"procedural\",\n"
            "    \"body\": \"Step-by-step instructions or commands (e.g. check logs, run a safe diagnostic command, or explain resolution)\",\n"
            "    \"tags\": [\"tag1\", \"tag2\"]\n"
            "  },\n"
            "  \"edge_metadata\": {\n"
            "    \"condition\": \"The key word or phrase in the tool output that triggers this step\",\n"
            "    \"condition_type\": \"tool_output_match\"\n"
            "  },\n"
            "  \"reason\": \"Brief explanation of why this step is recommended\"\n"
            "}"
        )
        user_msg = (
            f"Stuck Node Title: {stuck_node['title']}\n"
            f"Stuck Node Body: {stuck_node['body']}\n"
            f"Stuck Node Tags: {stuck_node['tags']}\n"
            f"Problem Context (Tool Output / Error): {problem_context}\n"
        )
        
        # Multi-model fan-out check
        fan_out_enabled = settings.get("consult_fan_out_enabled", False)
        responses = []
        
        if fan_out_enabled:
            # Try fanning out to N providers
            active_provs = await get_active_providers(user_id)
            # Make sure we use unique providers
            active_provs = list(set(active_provs))[:3] # Up to 3
            if len(active_provs) > 1:
                tasks = []
                for p in active_provs:
                    try:
                        p_resolved = resolve_provider(user_id=user_id, feature="chat", preferred_provider=p)
                        tasks.append(run_single_consult(p_resolved, system_prompt, user_msg))
                    except Exception:
                        pass
                if tasks:
                    completed_tasks = await asyncio.gather(*tasks, return_exceptions=True)
                    for t in completed_tasks:
                        if isinstance(t, tuple):
                            responses.append(t[0])
            
        if not responses:
            # Single model consult fallback
            res_text, _ = await run_single_consult(resolved, system_prompt, user_msg)
            responses.append(res_text)
            
        # Clean responses
        import re
        responses = [re.sub(r"```json|```", "", r).strip() for r in responses]
        
        # Synthesis consensus vs divergence
        synthesis_result, synth_reason = await synthesize_responses(ws_id, user_id, responses)
        
        primary_response = responses[0]
        try:
            proposal_dict = json.loads(primary_response)
        except Exception:
            return {"status": "error", "message": "Failed to parse generated troubleshooting proposal as JSON."}
            
        # 4. Safety classification (Track B)
        # We classify safety of the suggested action / node body
        new_node_dict = proposal_dict.get("new_node") or {}
        safety_proposal = {
            "title": new_node_dict.get("title"),
            "body": new_node_dict.get("body"),
            "content_type": "procedural",
            "suggested_action": proposal_dict
        }
        
        safety_class = await classify_safety(safety_proposal, ws_id)
        
        session_id = generate_id("con")
        
        if safety_class == "dangerous":
            # Dangerous: hard block!
            with db_cursor(commit=True) as cur:
                # Save session as dangerous
                cur.execute(
                    """
                    INSERT INTO consult_sessions (id, workspace_id, stuck_node_id, problem_context, mode, synthesis_result, inquiry_path_id, metadata)
                    VALUES (%s, %s, %s, %s, %s, 'dangerous', %s, %s)
                    """,
                    (session_id, ws_id, stuck_node_id, problem_context, mode, inquiry_path_id, json.dumps(proposal_dict))
                )
                
                # Write gap node
                cur.execute(
                    """
                    SELECT id FROM memory_nodes 
                    WHERE workspace_id = %s 
                      AND content_type = 'gap' 
                      AND title = %s 
                      AND status = 'active'
                    """,
                    (ws_id, f"Dangerous Block at {stuck_node['title']}")
                )
                if not cur.fetchone():
                    from services.nodes import create_node_in_db
                    gap_payload = {
                        "title": f"Dangerous Block at {stuck_node['title']}",
                        "content_type": "gap",
                        "content_format": "plain",
                        "body": f"Consult generated a dangerous proposal containing blocked commands. Synthesis: {synth_reason}",
                        "tags": ["dangerous_block", "consult_gap"],
                        "visibility": "private",
                        "author": user_id,
                        "status": "active"
                    }
                    create_node_in_db(cur, ws_id, gap_payload)
            
            # Send Notification
            send_consult_notification(
                ws_id=ws_id,
                session_id=session_id,
                classification="dangerous",
                action_taken="blocked",
                proposal=proposal_dict
            )
            
            return {
                "status": "blocked",
                "classification": "dangerous",
                "message": "The generated troubleshooting step was classified as DANGEROUS and blocked. A gap node has been created.",
                "session_id": session_id
            }
            
        elif safety_class == "risky" or synthesis_result == "divergent":
            # Risky or divergent: Force escalation to audit proposal (ignoring trust tier)
            reason = f"Synthesizer found model divergence: {synth_reason}" if synthesis_result == "divergent" else "Contains potentially risky commands or system changes."
            
            # Add stuck_node_id to suggested_action so we know where to connect the proceeds_to edge
            proposal_dict["stuck_node_id"] = stuck_node_id
            
            with db_cursor(commit=True) as cur:
                prop_row = create_proposal(
                    cur=cur,
                    workspace_id=ws_id,
                    reviewer="consult",
                    category="consult_escalation",
                    target_ids=[stuck_node_id],
                    reasoning=reason,
                    evidence={"problem_context": problem_context, "synthesis": synth_reason, "responses": responses, "safety": safety_class},
                    suggested_action=proposal_dict,
                    severity="high" if safety_class == "risky" else "mid"
                )
                prop_id = prop_row["id"] if prop_row else None
                
                cur.execute(
                    """
                    INSERT INTO consult_sessions (id, workspace_id, stuck_node_id, problem_context, mode, synthesis_result, inquiry_path_id, audit_proposal_id, metadata)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                    """,
                    (session_id, ws_id, stuck_node_id, problem_context, mode, safety_class if safety_class == "risky" else "divergent", inquiry_path_id, prop_id, json.dumps(proposal_dict))
                )
                
            # Send Notification (事前通知 "待決議")
            send_consult_notification(
                ws_id=ws_id,
                session_id=session_id,
                classification=safety_class if safety_class == "risky" else "divergent",
                action_taken="escalated",
                proposal=proposal_dict,
                proposal_id=prop_id
            )
            
            # D4-T14: Synchronous blocking notification (risky commands)
            if safety_class == "risky" and prop_id:
                timeout = 10.0  # Keep it short for testing/UX (10 seconds or 30 seconds)
                poll_interval = 0.5
                elapsed = 0.0
                approved = False
                while elapsed < timeout:
                    await asyncio.sleep(poll_interval)
                    elapsed += poll_interval
                    with db_cursor() as cur:
                        cur.execute("SELECT status FROM audit_proposals WHERE id = %s", (prop_id,))
                        p_row = cur.fetchone()
                        if p_row:
                            if p_row["status"] == "accepted":
                                approved = True
                                break
                            elif p_row["status"] in ("dismissed", "expired"):
                                break
                
                if approved:
                    # Automatically merge it! (Self-healing recovery)
                    with db_cursor(commit=True) as cur:
                        from services.nodes import create_node_in_db
                        new_node_payload = {
                            "title": new_node_dict.get("title"),
                            "content_type": "procedural",
                            "content_format": "plain",
                            "body": new_node_dict.get("body", ""),
                            "tags": new_node_dict.get("tags", []),
                            "visibility": "private",
                            "author": user_id,
                            "source_type": "ai",
                            "status": "active"
                        }
                        new_node_row = create_node_in_db(cur, ws_id, new_node_payload)
                        new_node_id = new_node_row["id"]
                        
                        from services.edges import create_edge_in_db
                        edge_data = {
                            "from_id": stuck_node_id,
                            "to_id": new_node_id,
                            "relation": "proceeds_to",
                            "weight": 1.0,
                            "half_life_days": 365,
                            "pinned": False,
                            "metadata": proposal_dict.get("edge_metadata") or {}
                        }
                        create_edge_in_db(cur, ws_id, edge_data)
                        
                        cur.execute(
                            "UPDATE memory_nodes SET status = 'archived', updated_at = now() WHERE id = %s AND content_type = 'gap'",
                            (stuck_node_id,)
                        )
                    
                    return {
                        "status": "merged",
                        "new_node_id": new_node_id,
                        "session_id": session_id
                    }
                else:
                    return {
                        "status": "blocked",
                        "classification": "risky",
                        "message": "Timed out or rejected waiting for human approval (fail-closed).",
                        "session_id": session_id
                    }
            
            return {
                "status": "escalated",
                "classification": safety_class,
                "reason": reason,
                "proposal_id": prop_id,
                "session_id": session_id
            }
            
        else:  # safety_class == "safe" and synthesis_result == "consensus"
            # Safe: Check trust tier
            trust_tier = workspace.get("consult_trust_tier", "ask")
            proposal_dict["stuck_node_id"] = stuck_node_id
            
            if trust_tier == "full_trust":
                # Auto merge! (C2)
                with db_cursor(commit=True) as cur:
                    # 1. Create node
                    from services.nodes import create_node_in_db
                    new_node_payload = {
                        "title": new_node_dict.get("title"),
                        "content_type": "procedural",
                        "content_format": "plain",
                        "body": new_node_dict.get("body", ""),
                        "tags": new_node_dict.get("tags", []),
                        "visibility": "private",
                        "author": user_id,
                        "source_type": "ai",
                        "status": "active"
                    }
                    new_node_row = create_node_in_db(cur, ws_id, new_node_payload)
                    new_node_id = new_node_row["id"]
                    
                    # 2. Create proceeds_to edge
                    from services.edges import create_edge_in_db
                    edge_data = {
                        "from_id": stuck_node_id,
                        "to_id": new_node_id,
                        "relation": "proceeds_to",
                        "weight": 1.0,
                        "half_life_days": 365,
                        "pinned": False,
                        "metadata": proposal_dict.get("edge_metadata") or {}
                    }
                    create_edge_in_db(cur, ws_id, edge_data)
                    
                    # Archive stuck gap node if it exists
                    cur.execute(
                        "UPDATE memory_nodes SET status = 'archived', updated_at = now() WHERE id = %s AND content_type = 'gap'",
                        (stuck_node_id,)
                    )
                    
                    # Save session
                    cur.execute(
                        """
                        INSERT INTO consult_sessions (id, workspace_id, stuck_node_id, problem_context, mode, synthesis_result, inquiry_path_id, metadata)
                        VALUES (%s, %s, %s, %s, %s, 'safe', %s, %s)
                        """,
                        (session_id, ws_id, stuck_node_id, problem_context, mode, inquiry_path_id, json.dumps(proposal_dict))
                    )
                    
                # Send Notification (事後通知 "已新增")
                send_consult_notification(
                    ws_id=ws_id,
                    session_id=session_id,
                    classification="safe",
                    action_taken="auto_merged",
                    proposal=proposal_dict
                )
                
                return {
                    "status": "merged",
                    "new_node_id": new_node_id,
                    "session_id": session_id
                }
                
            else:  # trust_tier == "ask"
                # Escalated (pre-merge pending review)
                with db_cursor(commit=True) as cur:
                    prop_row = create_proposal(
                        cur=cur,
                        workspace_id=ws_id,
                        reviewer="consult",
                        category="consult_escalation",
                        target_ids=[stuck_node_id],
                        reasoning="Troubleshooting consult generated a new safe recommendation. Pending review.",
                        evidence={"problem_context": problem_context, "safety": "safe"},
                        suggested_action=proposal_dict,
                        severity="low"
                    )
                    prop_id = prop_row["id"] if prop_row else None
                    
                    cur.execute(
                        """
                        INSERT INTO consult_sessions (id, workspace_id, stuck_node_id, problem_context, mode, synthesis_result, inquiry_path_id, audit_proposal_id, metadata)
                        VALUES (%s, %s, %s, %s, %s, 'safe', %s, %s, %s)
                        """,
                        (session_id, ws_id, stuck_node_id, problem_context, mode, inquiry_path_id, prop_id, json.dumps(proposal_dict))
                    )
                    
                # Send Notification (事前通知 "待決議")
                send_consult_notification(
                    ws_id=ws_id,
                    session_id=session_id,
                    classification="safe",
                    action_taken="escalated",
                    proposal=proposal_dict,
                    proposal_id=prop_id
                )
                
                return {
                    "status": "escalated",
                    "classification": "safe",
                    "proposal_id": prop_id,
                    "session_id": session_id
                }
