-- =========================================================
-- 003_seed_spec_kb.sql
-- Auto-generated by scripts/seed_spec_kb.py — do not edit by hand.
-- Seeds the MemTrace spec knowledge base (ws_spec0001).
-- Runs automatically on Docker first-init via docker-entrypoint-initdb.d.
-- =========================================================

SET client_encoding = 'UTF8';

-- System user (idempotent)
INSERT INTO users (id, email, display_name, email_verified)
VALUES ('system', 'system@memtrace.internal', 'MemTrace System', true)
ON CONFLICT (id) DO NOTHING;

-- Spec workspace
INSERT INTO workspaces (id, name_zh, name_en, visibility, kb_type, owner_id)
VALUES ('ws_spec0001', '規格知識庫', 'Spec Knowledge Base', 'public', 'evergreen', 'system')
ON CONFLICT (id) DO NOTHING;

-- Nodes
INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_a001','1.0','ws_spec0001','AI Provider 與 API Key 自管','AI provider and self-managed API keys','procedural','markdown',
   'MemTrace 不自營 AI 推論服務。所有 AI 功能由使用者選擇的第三方供應商提供。

**官方支援的 Provider**：

| Provider | 識別碼 | 預設 Chat 模型 | Embedding 模型 | 維度 |
|----------|--------|---------------|---------------|------|
| OpenAI | `openai` | `gpt-4o-mini` | `text-embedding-3-small` | 1536 |
| Anthropic | `anthropic` | `claude-haiku-4-5-20251001` | `voyage-3-lite` | 1024 |
| Google Gemini | `gemini` | `gemini-2.0-flash` | `text-embedding-004` | 768 |

**Embedding 維度限制**：每個工作區的 embedding 維度在建立時固定（`workspaces.embedding_provider` + `embedding_dim`），**不可變更**。不同 provider 產生的向量維度不同，無法跨 provider 比較 cosine similarity。

**API Key 儲存**：CLI 存於 `~/.memtrace/config.json`（chmod 600），UI 存於 localStorage 或加密寫入 `user_ai_keys`。Key **永不**傳送至 MemTrace 伺服器以外的任何地方。

**社群 Provider**：透過 `packages/api/core/ai.py` 的 `AIProvider` Protocol 可加入新 provider（Mistral、Cohere、Ollama、vLLM 等）。實作後在 `PROVIDER_REGISTRY` 註冊即可，不需修改 router 或資料庫 schema。

**未來商業模式**：可能提供 MemTrace 代管額度（免費層 + 付費方案）；架構透過 provider interface 抽象，日後切換不影響上層邏輯。','MemTrace does not operate its own AI inference service. All AI features are powered by the user''s chosen third-party provider.

**Officially supported providers**:

| Provider | Identifier | Default chat model | Embedding model | Dim |
|----------|------------|--------------------|-----------------|-----|
| OpenAI | `openai` | `gpt-4o-mini` | `text-embedding-3-small` | 1536 |
| Anthropic | `anthropic` | `claude-haiku-4-5-20251001` | `voyage-3-lite` | 1024 |
| Google Gemini | `gemini` | `gemini-2.0-flash` | `text-embedding-004` | 768 |

**Embedding dimension constraint**: Each workspace fixes its embedding dimension at creation time (`workspaces.embedding_provider` + `embedding_dim`) and it is **immutable**. Different providers produce vectors of different dimensions; nodes embedded with different models cannot be compared via cosine similarity.

**API key storage**: CLI in `~/.memtrace/config.json` (chmod 600); UI in localStorage or encrypted in `user_ai_keys`. Keys are **never** transmitted to any MemTrace server.

**Community providers**: Add new providers via the `AIProvider` Protocol in `packages/api/core/ai.py` (Mistral, Cohere, Ollama, vLLM, etc.). Implement and register in `PROVIDER_REGISTRY` — no router or schema changes needed.

**Future business model**: a managed credit option (free tier + paid) may be introduced. The provider interface abstraction lets this swap in without touching extraction logic.',ARRAY['ai', 'api-key', 'provider', 'security', 'gemini', 'embedding']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_a002','1.0','ws_spec0001','文件攝入與 AI 節點萃取','Document ingestion and AI node extraction','procedural','markdown',
   '支援格式：`.md`、`.txt`、`.pdf`、`.docx`。萃取流程：

1. AI 依文件結構（標題、段落）切割成候選塊
2. 各塊被分類為 Content Type
3. 生成雙語標題與內文草稿
4. 提議候選 Edge（依語意相近與文件順序）

所有結果進入 **Review Queue**，不自動 commit。萃取節點的 source_type 預設為 `ai_generated`，人工無修改接受 → `ai_verified`，人工修改後接受 → `human`。每個節點記錄 source_document 與 extraction_model。','Supported formats: `.md`, `.txt`, `.pdf`, `.docx`. Extraction flow:

1. AI segments the document into candidate chunks by structure (headings, paragraphs)
2. Each chunk is classified into a Content Type
3. Bilingual title and body drafts are generated
4. Candidate Edges are proposed based on semantic proximity and document order

All results enter the **Review Queue** — never auto-committed. Extracted node source_type defaults to `ai_generated`; accepted without edits → `ai_verified`; accepted after edits → `human`. Each node records source_document and extraction_model.',ARRAY['ai', 'ingestion', 'extraction', 'document']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_a003','1.0','ws_spec0001','Review Queue：人工審核 AI 萃取結果','Review Queue: human review of AI-extracted candidates','procedural','plain',
   'AI 萃取的候選節點不自動進入知識庫，必須通過人工審核。三種操作：Accept（接受原樣）、Edit then Accept（修改後接受）、Reject（捨棄）。支援批次操作（Accept all / Reject all）。至少需接受一個節點才能關閉審核步驟。審核完成後，被接受的節點以正確的 source_type 寫入知識庫，被拒絕的候選永久丟棄。這是 MemTrace 確保 AI 生成內容不污染知識庫的核心機制。','AI-extracted candidate nodes do not enter the Knowledge Base automatically — they must pass human review. Three actions: Accept (as-is), Edit then Accept (modify before committing), Reject (discard). Bulk operations (Accept all / Reject all) are supported. At least one node must be accepted before the review step can be closed. After review, accepted nodes are written with the correct source_type; rejected candidates are permanently discarded. This is MemTrace''s core mechanism for preventing AI-generated content from polluting the Knowledge Base.',ARRAY['ai', 'review-queue', 'quality-control', 'ingestion']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_a004','1.0','ws_spec0001','對話式問答（Conversational Q&A）','Conversational Q&A against the knowledge base','procedural','plain',
   'viewer 以上角色可對知識庫進行自然語言問答。Q&A 為唯讀操作，不修改知識庫內容。

執行流程：
1. 使用者傳送訊息
2. search_nodes(query) → 取得最相關的 5 個節點
3. traverse(最高分節點, depth=1) → 補充鄰近上下文（可選）
4. 組合 prompt：system 說明（只使用提供的節點作答，並引用節點 ID）+ 節點內容 + 使用者問題
5. 呼叫 AI（使用工作區 AI provider 設定，§16.5）
6. 回傳：answer + cited_nodes[] + tokens_used + session_id

API：
- POST /workspaces/{ws_id}/chat — 發送訊息（傳入 session_id 可延續對話，不傳則建立新 session）
- GET /workspaces/{ws_id}/chat/sessions — 列出使用者的 session 清單
- GET /workspaces/{ws_id}/chat/sessions/{session_id} — 取得完整對話紀錄

多輪對話：session 中最近 10 則訊息會一起送入 context window 以支援連續問答。

Schema：chat_sessions（id, workspace_id, user_id, created_at, updated_at）和 chat_messages（id, session_id, role user/assistant, content, cited_nodes[], tokens_used, created_at）。

注意：即使是 public 工作區，Q&A 也需要登入。未認證使用者無法使用此功能。','Any member with viewer role or above can ask natural-language questions against a workspace''s KB. Q&A is read-only — it never writes to the KB.

Execution flow:
1. User sends a message
2. search_nodes(query) → retrieves top-5 relevant nodes
3. traverse(top node, depth=1) → adds neighbour context (optional, improves multi-hop answers)
4. Build prompt: system instruction (answer only from provided nodes, cite node IDs) + node content blocks + user question
5. Call AI (uses workspace AI provider config, §16.5)
6. Return: answer + cited_nodes[] + tokens_used + session_id

API:
- POST /workspaces/{ws_id}/chat — send message (pass session_id to continue a conversation; omit to start a new session)
- GET /workspaces/{ws_id}/chat/sessions — list the caller''s sessions
- GET /workspaces/{ws_id}/chat/sessions/{session_id} — get full message history

Multi-turn: the last 10 messages in the session are included in the context window for conversational continuity.

Schema: chat_sessions (id, workspace_id, user_id, created_at, updated_at) and chat_messages (id, session_id, role user/assistant, content, cited_nodes[], tokens_used, created_at).

Note: Q&A requires authentication even on public workspaces. Unauthenticated users cannot use this feature.',ARRAY['ai', 'chat', 'q&a', 'conversational', 'session', 'read-only']::text[],'public',
   'system','2026-04-12T00:00:00Z','f3a4b5c6d7e8f3a4b5c6d7e8f3a4b5c6d7e8f3a4b5c6d7e8f3a4b5c6d7e8f3a4','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_d001','1.0','ws_spec0001','Memory Node：知識的最小單位','Memory Node: the atomic unit of knowledge','factual','markdown',
   'Memory Node 是 MemTrace 中知識的最小單位。每個節點捕捉**一個**想法，包含：

- **雙語標題與內文**（zh-TW + en），各自獨立
- **Content Type**：`factual` / `procedural` / `preference` / `context` / `source_document`
- **Format**：`plain` 或 `markdown`
- **Tags**：字串陣列，用於分類與搜尋
- **Visibility**：`public` / `team` / `private`
- **Provenance**：作者、建立時間、SHA-256 簽章、source_type
- **Trust**：四維度信任分數
- **Traversal**：走訪計數與不重複訪客數
- **Status**：`active` / `archived`（archived 從預設視圖隱藏，不刪除）

**並行寫入相關欄位**（§17）：
- `version` — 樂觀鎖整數，每次 UPDATE 自動 +1；PATCH 必須帶 `X-Node-Version` header
- `conflict_status` — `flagged` / `resolved`，由衝突檢測寫入
- `conflict_detail` — JSONB，記錄衝突類型與相關節點

**來源文件追溯欄位**（§20）：
- `source_doc_node_id` — 指向 `source_document` 類型節點，用於追溯萃取來源
- `source_paragraph_ref` — 字串，標記在原文件中的段落位置（如 `page:3, para:2` 或 `00:14:32-00:15:01`）

節點 ID 格式：`mem_<hex8>`，例如 `mem_a1b2c3d4`。','A Memory Node is the atomic unit of knowledge in MemTrace. Each node captures **one** idea and contains:

- **Bilingual title + body** (zh-TW + en), independently authored
- **Content Type**: `factual` / `procedural` / `preference` / `context` / `source_document`
- **Format**: `plain` or `markdown`
- **Tags**: string array for classification and search
- **Visibility**: `public` / `team` / `private`
- **Provenance**: author, creation timestamp, SHA-256 signature, source_type
- **Trust**: four-dimension trust score
- **Traversal**: visit count and unique visitor count
- **Status**: `active` / `archived` (archived nodes are hidden from default views, not deleted)

**Concurrency fields** (§17):
- `version` — optimistic-lock integer, auto-incremented on every UPDATE; PATCH must include `X-Node-Version` header
- `conflict_status` — `flagged` / `resolved`, set by the conflict detection job
- `conflict_detail` — JSONB, records conflict type and related node

**Source-document traceability fields** (§20):
- `source_doc_node_id` — references a `source_document`-type node for extraction traceability
- `source_paragraph_ref` — string marking the original location (e.g. `page:3, para:2` or `00:14:32-00:15:01`)

Node ID format: `mem_<hex8>`, e.g. `mem_a1b2c3d4`.',ARRAY['data-model', 'schema', 'core', 'version', 'conflict']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_d002','1.0','ws_spec0001','Edge：有向有型的關係','Edge: a typed, directed relationship','factual','markdown',
   'Edge 連接兩個 Memory Node，方向為 `from → to`。每條 Edge 包含：

- **Relation type**：depends_on / extends / related_to / contradicts
- **Weight**：0–1，反映關係強度；由 decay 與 co-access boost 動態更新
- **Co-access count**：被共同存取的次數
- **Decay 參數**：half_life_days（預設 30）、min_weight（預設 0.1）
- **Traversal**：走訪次數、平均評分（1–5）、評分人數

Edge ID 格式：`edge_<hex8>`。同一對節點間相同 relation type 的 Edge 不重複。','An Edge connects two Memory Nodes with direction `from → to`. Each edge contains:

- **Relation type**: depends_on / extends / related_to / contradicts
- **Weight**: 0–1, reflecting relationship strength; dynamically updated by decay and co-access boost
- **Co-access count**: how many times accessed together
- **Decay parameters**: half_life_days (default 30), min_weight (default 0.1)
- **Traversal**: visit count, average rating (1–5), rating count

Edge ID format: `edge_<hex8>`. Duplicate edges (same from, to, relation) are rejected.',ARRAY['data-model', 'schema', 'graph', 'core']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_d003','1.0','ws_spec0001','Content Type：節點的知識性質','Content Type: the nature of knowledge in a node','factual','markdown',
   '每個 Memory Node 必須標記一種 Content Type：

| Type | 說明 | 例子 |
|------|------|------|
| `factual` | 陳述性事實 | 「pgvector 支援 cosine similarity」 |
| `procedural` | 步驟流程 | 「如何設定 Google OAuth」 |
| `preference` | 偏好或決策 | 「我們選擇 bcrypt 而非 argon2」 |
| `context` | 背景脈絡 | 「這個專案採用雙語設計的原因」 |
| `source_document` | 攝入時保留的原始文件（§20）| 一個會議錄音逐字稿、一份 PDF 全文 |

**`source_document` 特性**：由 `ingest` 流程自動建立，body 為文件全文或逐字稿，預設從 Graph View / 搜尋 / Q&A context 中**排除**。萃取出的節點透過 `source_doc_node_id` + `source_paragraph_ref` 反向連結到原始段落。

Content Type 影響：搜尋過濾、AI 萃取分類、預設 decay half-life（ephemeral 工作區）、Export Scope 配對（`procedural` → user-manual，`factual` → functional-spec 等）。','Every Memory Node must be tagged with a Content Type:

| Type | Description | Example |
|------|-------------|---------|
| `factual` | Declarative facts | "pgvector supports cosine similarity" |
| `procedural` | Step-by-step process | "How to configure Google OAuth" |
| `preference` | Preferences or decisions | "We chose bcrypt over argon2" |
| `context` | Background context | "Why this project uses bilingual design" |
| `source_document` | Original document retained at ingestion (§20) | A meeting transcript, a full PDF |

**`source_document` characteristics**: Created automatically by the `ingest` flow; body holds the full text or transcript. **Excluded by default** from Graph View / search / Q&A context. Extracted nodes link back to the original passage via `source_doc_node_id` + `source_paragraph_ref`.

Content Type affects: search filtering, AI extraction classification, default decay half-life (ephemeral workspaces), and Export Scope matching (`procedural` → user-manual, `factual` → functional-spec, etc.).',ARRAY['data-model', 'schema', 'content-type', 'source-document']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1','human',
   0.95,0.95,1.0,0.9,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_d004','1.0','ws_spec0001','Trust 系統：信任如何被計算','Trust system: how trust is calculated','factual','markdown',
   '每個 Memory Node 帶有一個 0–1 的綜合信任分數，由四個維度合成：

| 維度 | 說明 | 建立時預設 |
|------|------|----------|
| `accuracy` | 事實正確性 | 0.5 |
| `freshness` | 時效性 | 1.0 |
| `utility` | 實用程度 | 0.5 |
| `author_rep` | 作者信譽 | 0.5 |

信任分數隨社群投票（up/down）與驗證次數持續更新。內容以 SHA-256 簽章防偽，每次儲存重新計算。Trust score < 0.3 的節點標記警告；< 0.1 的節點從公開索引移除。','Every Memory Node carries a composite trust score (0–1) derived from four dimensions:

| Dimension | Description | Default at creation |
|-----------|-------------|--------------------|
| `accuracy` | Factual correctness | 0.5 |
| `freshness` | Timeliness | 1.0 |
| `utility` | Practical usefulness | 0.5 |
| `author_rep` | Author reputation | 0.5 |

Trust scores are updated continuously by community votes (up/down) and verification counts. Content is SHA-256 signed on every save. Nodes with score < 0.3 are flagged; nodes < 0.1 are removed from the public index.',ARRAY['data-model', 'trust', 'anti-forgery']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3','human',
   0.95,0.95,1.0,0.9,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_d005','1.0','ws_spec0001','Provenance：來源與可溯性','Provenance: origin and traceability','factual','plain',
   '每個節點的 provenance 物件記錄知識的來源資訊：author（作者）、created_at（建立時間）、signature（SHA-256 內容雜湊）、source_type（human / ai_generated / ai_verified）。編輯後新增 updated_at。AI 萃取的節點額外記錄 source_document（來源文件）與 extraction_model（使用的 AI 模型）。複製到其他知識庫的節點記錄 copied_from.node_id 與 copied_from.workspace_id。Provenance 永遠記錄，但不構成存取限制。','The provenance object on each node records the knowledge''s origin: author, created_at, signature (SHA-256 content hash), source_type (human / ai_generated / ai_verified). updated_at is added on any edit. AI-extracted nodes additionally record source_document (the source file) and extraction_model (the AI model used). Nodes copied across Knowledge Bases record copied_from.node_id and copied_from.workspace_id. Provenance is always recorded but does not restrict access.',ARRAY['data-model', 'provenance', 'traceability']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4','human',
   0.95,0.95,1.0,0.9,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_d006','1.0','ws_spec0001','Traversal Tracking：走訪計數','Traversal Tracking: measuring real usage','factual','plain',
   '節點與 Edge 各自記錄走訪數據。節點記錄：traversal_count（總走訪次數）、unique_traverser_count（不重複訪客數）。Edge 記錄：traversal_count、rating_avg（1–5 平均評分，無評分時為 null）、rating_count。走訪透過 API 的 POST /nodes/{id}/traverse 或 POST /edges/{id}/traverse 記錄。MCP tool traverse_edge 也會觸發計數。這些數字反映知識的實際使用頻率，不只是被記錄的事實。','Nodes and edges each track traversal data. Nodes record: traversal_count (total visits) and unique_traverser_count (distinct actors). Edges record: traversal_count, rating_avg (1–5 average, null if no ratings), and rating_count. Traversals are recorded via POST /nodes/{id}/traverse or POST /edges/{id}/traverse in the REST API, or via the MCP tool traverse_edge. These numbers reflect actual knowledge usage frequency, not just what was recorded.',ARRAY['data-model', 'traversal', 'usage-tracking']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5','human',
   0.95,0.95,1.0,0.9,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_g001','1.0','ws_spec0001','Decay：Edge 權重的自然衰減','Decay: natural weight reduction on edges','factual','markdown',
   'Edge 權重隨時間依以下公式衰減（v1）：

```
weight(t) = w₀ × 0.5 ^ (days_since_last_access / half_life)
```

**核心原則**：**Decay 塑造注意力，不塑造存在**。沒有東西因 decay 而被刪除。

**Edge 狀態轉換**：當 `weight < min_weight`（預設 0.1），Edge 進入 `faded` 狀態：
- 從預設 Graph View 與 traversal 結果隱藏
- 仍存於資料庫（`status = ''faded''`），可由原作者或 admin 還原
- API 加 `include_faded=true` 仍可查詢

**節點層級**：
- `evergreen` 工作區：節點本身依「觀察期內走訪計數」歸檔（§7.3），不受時間衰減
- `ephemeral` 工作區：當所有相連 Edge 皆 faded，節點自動 archived

**Pinned 例外**：`pinned: true` 的節點與 Edge 完全豁免於衰減與計數歸檔。

衰減觸發：每日由 `apply_edge_decay()` SQL 函式執行（鏡射 `packages/core/src/decay.ts`）。','Edge weight decays over time according to (v1):

```
weight(t) = w₀ × 0.5 ^ (days_since_last_access / half_life)
```

**Core principle**: **Decay shapes attention, not existence.** Nothing is deleted by decay alone.

**Edge state transition**: When `weight < min_weight` (default 0.1), the edge transitions to `faded`:
- Hidden from default Graph View and traversal results
- Still stored in the database (`status = ''faded''`); restorable by the original author or admin
- Queryable via API with `include_faded=true`

**Node level**:
- `evergreen` workspace: nodes are archived based on traversal count within an observation window (§7.3), not time-based
- `ephemeral` workspace: when all connected edges are faded, the node is auto-archived

**Pinned exemption**: Nodes and edges with `pinned: true` are fully exempt from both time-decay and traversal-count archiving.

Trigger: daily by the `apply_edge_decay()` SQL function (mirrors `packages/core/src/decay.ts`).',ARRAY['graph-mechanics', 'decay', 'weight', 'faded', 'archive']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_g002','1.0','ws_spec0001','Co-Access Boost：共存取加成','Co-Access Boost: strengthening edges through use','factual','markdown',
   '當兩個相連節點在同一情境下被循序或同時存取（Co-Access），對應 Edge 的 weight 會得到加成，加成量依 relation type 而異：

| Relation | Boost |
|----------|-------|
| `depends_on` | +0.30 |
| `extends` | +0.20 |
| `related_to` | +0.15 |
| `contradicts` | +0.10 |

同時觸發：co_access_count +1、last_co_accessed 更新、weight 上限 1.0。API 路徑 POST /edges/{id}/traverse 或 MCP tool traverse_edge 皆會觸發 co-access boost。','When two connected nodes are accessed sequentially or simultaneously in the same context (Co-Access), the corresponding edge''s weight receives a boost based on relation type:

| Relation | Boost |
|----------|-------|
| `depends_on` | +0.30 |
| `extends` | +0.20 |
| `related_to` | +0.15 |
| `contradicts` | +0.10 |

Also increments co_access_count, updates last_co_accessed, and caps weight at 1.0. Triggered by POST /edges/{id}/traverse or MCP tool traverse_edge.',ARRAY['graph-mechanics', 'co-access', 'boost', 'weight']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_g003','1.0','ws_spec0001','Edge 關係類型：四種語意方向','Edge relation types: four semantic directions','factual','markdown',
   '| Relation | 語意 | 使用時機 |
|----------|------|----------|
| `depends_on` | 來源節點的成立依賴目標節點 | A 的流程前提是 B 的概念 |
| `extends` | 來源節點延伸或補充目標節點 | A 是 B 的進階版本 |
| `related_to` | 有相關性但無明確依賴方向 | A 和 B 都屬於同一主題 |
| `contradicts` | 來源節點的內容與目標節點矛盾 | A 的結論與 B 相衝突 |

選擇正確的 relation type 很重要，因為它決定了 co-access boost 的強度，以及 AI agent 在遍歷圖時如何解讀關係。','| Relation | Semantics | When to use |
|----------|-----------|-------------|
| `depends_on` | Source requires target to be valid | A''s process presupposes B''s concept |
| `extends` | Source extends or supplements target | A is an advanced version of B |
| `related_to` | Related without clear dependency direction | A and B belong to the same topic |
| `contradicts` | Source conflicts with target | A''s conclusion conflicts with B |

Choosing the correct relation type matters: it determines co-access boost strength and how AI agents interpret the relationship when traversing the graph.',ARRAY['graph-mechanics', 'relation-type', 'edge', 'schema']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2b3c4d5e6f7a2','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_i001','1.0','ws_spec0001','使用者認證：Email 與密碼','User authentication: email and password','procedural','plain',
   'MemTrace 採用 Email + Password 認證路徑。安全措施包括：bcrypt 雜湊（cost ≥ 12）、密碼政策（8–128 字元、大小寫+數字、HaveIBeenPwned 洩漏檢查）、email 驗證信（24 小時效期）、失敗 5 次鎖定 15 分鐘。登入後核發 JWT Session（7 天），透過 Authorization: Bearer 標頭傳遞，登出以 blocklist 立即失效。目前不支援第三方 OAuth 登入，以簡化認證表面並減少外部依賴。','MemTrace uses Email + Password authentication. Security measures include: bcrypt hash (cost ≥ 12), password policy (8–128 chars, upper+lower+digit, HaveIBeenPwned check), verification email (24h expiry), and 5-failure lockout for 15 minutes. Upon login, a JWT session (7 days) is issued and passed via the Authorization: Bearer header. Logout is handled via an immediate blocklist. Third-party OAuth is currently not supported to simplify the authentication surface and reduce external dependencies.',ARRAY['auth', 'security', 'jwt', 'password-policy']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5','human',
   0.95,0.95,1.0,0.9,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_i002','1.0','ws_spec0001','REST API 與外部 API Key','REST API and external API keys','factual','markdown',
   '外部服務與腳本以 **API Key** 認證（格式：`mt_live_<hex>`），而非 session JWT。Key 可綁定至特定 workspace 或跨 workspace，建立後完整金鑰只顯示一次。四種 scope：

| Scope | 權限 |
|-------|------|
| `kb:read` | 讀取 KB、節點、Edge |
| `kb:write` | 建立與編輯節點、Edge |
| `node:traverse` | 記錄走訪事件 |
| `node:rate` | 提交路徑評分（1–5）|

所有 API 端點前綴 `/api/v1`，使用 `Authorization: Bearer` 傳遞 key 或 token（伺服器依前綴區分）。','External services and scripts authenticate with **API Keys** (format: `mt_live_<hex>`), not session JWTs. Keys may be scoped to a specific workspace or valid across all. Full key value shown only once at creation. Four scopes:

| Scope | Grants |
|-------|--------|
| `kb:read` | Read KBs, nodes, edges |
| `kb:write` | Create and edit nodes, edges |
| `node:traverse` | Record traversal events |
| `node:rate` | Submit path ratings (1–5) |

All API endpoints prefixed with `/api/v1`, using `Authorization: Bearer` for both keys and session tokens (server distinguishes by prefix).',ARRAY['api', 'api-key', 'access-control', 'integration']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_i003','1.0','ws_spec0001','MCP Server：AI Agent 整合','MCP Server: AI agent integration','factual','markdown',
   'MemTrace 實作 **Model Context Protocol (MCP)**，讓 AI agent（如 Claude Code）可以將 MemTrace 知識庫作為 context provider，無需直接讀取規格文件。

**Transport**：目前僅支援 stdio（`node packages/mcp/dist/index.js`）。

**當前實作工具（Tools）**：

| 工具 | 說明 |
|------|------|
| `search_nodes` | 關鍵字搜尋節點（中英文皆可），回傳完整內容 |
| `get_node` | 依 ID 取得特定節點完整內容與 metadata |
| `traverse` | 取得節點及其上下游關聯（depth=1 或 2）|
| `list_by_tag` | 依 tag 列出所有節點 |

**環境變數**：
- `MEMTRACE_API`：API base URL（預設 `http://localhost:8000/api/v1`）
- `MEMTRACE_WS`：Workspace ID（預設 `ws_spec0001`）
- `MEMTRACE_LANG`：顯示語言（預設 `zh-TW`）

**現有限制**：
每個 MCP server 實例只能查詢單一工作區（由 `MEMTRACE_WS` 固定）。若需查詢多個知識庫，目前 workaround 是在 `.mcp.json` 中為每個工作區啟動獨立實例，但工具名稱相同會造成 AI agent 混淆。

**已規劃但尚未實作**：
- 多工作區支援：工具加入可選 `workspace_id` 參數 + `list_workspaces` 工具
- Resources（`memtrace://node/{id}` 等 URI 讀取）
- 寫入工具（`create_node`、`update_node`、`create_edge`）
- HTTP + SSE transport
- `traverse_edge` 觸發 co-access boost

Agent 每次沿 Edge 移動時應呼叫 traverse 工具，讓常用路徑保持活躍，抵抗 decay。','MemTrace implements the **Model Context Protocol (MCP)**, allowing AI agents (e.g. Claude Code) to use MemTrace as a context provider without reading raw spec documents.

**Transport**: stdio only for now (`node packages/mcp/dist/index.js`).

**Currently implemented tools**:

| Tool | Description |
|------|-------------|
| `search_nodes` | Keyword search across nodes (Chinese and English), returns full content |
| `get_node` | Retrieve a specific node by ID with full content and metadata |
| `traverse` | Get a node plus its upstream/downstream associations (depth=1 or 2) |
| `list_by_tag` | List all nodes with a specific tag |

**Environment variables**:
- `MEMTRACE_API`: API base URL (default `http://localhost:8000/api/v1`)
- `MEMTRACE_WS`: Workspace ID (default `ws_spec0001`)
- `MEMTRACE_LANG`: Display language (default `zh-TW`)

**Current limitation**: Each MCP server instance is locked to a single workspace (set by `MEMTRACE_WS`). To query multiple knowledge bases, the current workaround is to start a separate instance per workspace in `.mcp.json`, but identical tool names cause confusion for AI agents.

**Planned but not yet implemented**:
- Multi-workspace support: optional `workspace_id` parameter on all tools + `list_workspaces` tool
- Resources (`memtrace://node/{id}` URI reads)
- Write tools (`create_node`, `update_node`, `create_edge`)
- HTTP + SSE transport
- `traverse_edge` to trigger co-access boost

Agents should call traverse when following an edge, keeping frequently used paths alive against decay.',ARRAY['mcp', 'ai-agent', 'integration', 'api']::text[],'public',
   'system','2026-04-11T00:00:00Z','c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_i004','1.0','ws_spec0001','存取控制與權限角色：viewer / contributor / admin','Access control and permission roles: viewer / contributor / admin','factual','plain',
   'MemTrace 採用類 git 的三層權限模型，適用於人類使用者與 AI 工具（含 MCP）。

角色定義：
- viewer：唯讀 + 問答 + 節點評分（rate）
- contributor：viewer 全部能力 + 提出修改建議（→ review queue，需管理員審核）
- admin：contributor 全部能力 + 直接寫入 + 審核提案 + 管理成員 + 邀請使用者 + 軟刪除/還原工作區

工作區擁有者（owner）永遠是 admin，不可降級。

API Key scope 對應：
- kb:read → viewer
- kb:propose → contributor
- kb:write → admin

MCP 工具遵守相同規則：kb:read key 無法呼叫 create_node；kb:propose key 可呼叫 propose_node；kb:write key 可直接寫入。

Contributor 提案流程：POST /workspaces/{ws_id}/proposals → review_queue（source_type = contributor_proposal）→ admin 審核後生效。

加入工作區的預設角色：
- 建立工作區 → admin（擁有者）
- 透過邀請連結加入 → 邀請建立時指定的角色
- 跨庫複製節點 → 不授予任何成員資格','MemTrace uses a git-inspired three-tier permission model that applies equally to human users and AI tools (including MCP).

Roles:
- viewer: read-only + Q&A chat + node rating (votes_up/down)
- contributor: all viewer capabilities + submit change proposals (→ review queue, requires admin approval)
- admin: all contributor capabilities + direct write + approve/reject proposals + manage members + invite users + soft-delete/restore workspace

The workspace owner is always admin and cannot be demoted.

API Key scope mapping:
- kb:read → viewer
- kb:propose → contributor
- kb:write → admin

MCP tools respect the same rules: a kb:read key cannot call create_node; a kb:propose key can call propose_node; a kb:write key can write directly.

Contributor proposal flow: POST /workspaces/{ws_id}/proposals → review_queue (source_type = contributor_proposal) → takes effect after admin approval.

Default role on join:
- Create workspace → admin (owner)
- Accept invite link → role embedded in the invite token by admin
- Cross-workspace node copy → no membership granted',ARRAY['access-control', 'permissions', 'roles', 'viewer', 'contributor', 'admin', 'mcp', 'api-key']::text[],'public',
   'system','2026-04-12T00:00:00Z','d1e2f3a4b5c6d1e2f3a4b5c6d1e2f3a4b5c6d1e2f3a4b5c6d1e2f3a4b5c6d1e2','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_k001','1.0','ws_spec0001','Knowledge Base：知識庫（Workspace）','Knowledge Base: the container workspace','factual','plain',
   'Knowledge Base（又稱 Workspace）是 Memory Node 與 Edge 的容器，對應一個獨立的知識領域或專案。每個使用者可建立多個知識庫。知識庫本身有共享層級（public / restricted / private），與節點的 visibility 各自獨立——有效存取權取兩者較嚴格的一方。知識庫可以從空白開始，也可以從一份文件啟動並由 AI 萃取節點。ID 格式：ws_<hex8>。','A Knowledge Base (Workspace) is the container for Memory Nodes and Edges, corresponding to an independent knowledge domain or project. Users can create multiple Knowledge Bases. A Knowledge Base has its own sharing level (public / restricted / private), independent from node-level visibility — effective access is the more restrictive of the two. A Knowledge Base may be started blank or bootstrapped from a document with AI extraction. ID format: ws_<hex8>.',ARRAY['knowledge-base', 'workspace', 'container']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4','human',
   0.95,0.95,1.0,0.9,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_k002','1.0','ws_spec0001','知識庫共享層級：四種可見性','Knowledge Base sharing levels: four visibility tiers','factual','markdown',
   '| 層級 | 識別碼 | 說明 |
|------|--------|------|
| 全公開 | `public` | 任何人（含未登入）皆可探索與閱讀 `public` 節點 |
| 有條件公開 | `conditional_public` | 任何人皆可看到圖譜結構（拓撲），但節點內容隱藏；可向管理員提交加入申請 |
| 限制公開 | `restricted` | 知識庫對非成員不可見，必須由 admin 明確邀請才能加入 |
| 私有 | `private` | 僅擁有者可見，無法發出邀請 |

**重要**：visibility 在建立時設定後**不可變更**（immutable）。任何 `PATCH /workspaces/{ws_id}` 含 `visibility` 欄位的請求一律回 `400 Immutable field: visibility`。建立時 UI 必須清楚顯示四個層級，使用者必須明確確認。

節點層級的 visibility（public / team / private）獨立於知識庫層級，最終存取權取兩者較嚴格的一方。','| Tier | Identifier | Description |
|------|------------|-------------|
| Public | `public` | Anyone (incl. unauthenticated) can discover and read `public` nodes |
| Conditional Public | `conditional_public` | Anyone can see graph topology, but node content is hidden; users may submit a join request to admins |
| Restricted | `restricted` | KB is invisible to non-members; entry requires explicit admin invitation |
| Private | `private` | Owner-only; invitations cannot be issued |

**Important**: visibility is **immutable** after creation. Any `PATCH /workspaces/{ws_id}` containing `visibility` is rejected with `400 Immutable field: visibility`. The creation UI must show all four tiers clearly with inline descriptions and require explicit user confirmation.

Node-level visibility (`public` / `team` / `private`) is independent of KB-level visibility — effective access is the more restrictive of the two.',ARRAY['knowledge-base', 'sharing', 'visibility', 'access-control', 'four-tier']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_k003','1.0','ws_spec0001','節點跨庫複製：可攜性','Cross-workspace node copy: portability','procedural','plain',
   '任何節點可被複製到另一個知識庫，但 Edge 不隨行。複製行為：目標庫中取得新 id；created_at 重設為複製時間；provenance.copied_from 記錄 { node_id, workspace_id } 供溯源；目標庫中 visibility 預設為 private；Trust 分數以快照帶入，兩邊後續互不影響；signature 在目標庫環境重新計算。CLI 指令：memtrace copy-node <node-id> --to <workspace-id>。API：POST /workspaces/{ws_id}/nodes（帶 copied_from 參數）。','Any node can be copied to another Knowledge Base, but its Edges are not copied. Copy behaviour: the target KB assigns a new id; created_at is reset to the copy time; provenance.copied_from records { node_id, workspace_id } for traceability; visibility defaults to private in the target KB; Trust scores are carried as a snapshot — subsequent changes in either KB do not affect the other; signature is recomputed in the target KB context. CLI: memtrace copy-node <node-id> --to <workspace-id>. API: POST /workspaces/{ws_id}/nodes (with copied_from parameter).',ARRAY['knowledge-base', 'portability', 'copy', 'provenance']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6','human',
   0.95,0.95,1.0,0.9,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_k004','1.0','ws_spec0001','工作區生命週期與軟刪除（30 天寬限期）','Workspace lifecycle and soft-delete (30-day grace period)','procedural','plain',
   '工作區有三個狀態：active（正常）、pending_deletion（軟刪除中）、deleted（已清除）。

軟刪除觸發：admin 呼叫 DELETE /workspaces/{ws_id}
- 設定 status = pending_deletion、deleted_at = NOW()
- 非 admin 成員立即失去存取
- Admin/owner 保留唯讀存取（可匯出資料）
- 通知郵件：第 0 天（刪除啟動）、第 25 天（5 天警告）、第 30 天（最終清除）

還原：在寬限期內 admin 呼叫 POST /workspaces/{ws_id}/restore
- status 回到 active，deleted_at 清空，所有成員存取恢復

自動清除：每日背景排程，清除 status = pending_deletion AND deleted_at < NOW() - INTERVAL ''30 days'' 的工作區（CASCADE DELETE：節點、邊、成員、邀請、對話紀錄全部刪除，不可還原）。

KB 類型寬限期差異：
- evergreen：30 天
- ephemeral：7 天

Schema 新增：
ALTER TABLE workspaces ADD COLUMN status TEXT NOT NULL DEFAULT ''active'' CHECK (status IN (''active'',''pending_deletion'',''deleted'')), ADD COLUMN deleted_at TIMESTAMPTZ;','Workspaces move through three states: active (normal), pending_deletion (soft-deleted, grace period active), deleted (purged from DB).

Soft-delete trigger: admin calls DELETE /workspaces/{ws_id}
- Sets status = pending_deletion, deleted_at = NOW()
- Non-admin members immediately lose access
- Admin/owner retains read-only access (for data export)
- Email notifications: day 0 (deletion initiated), day 25 (5-day warning), day 30 (final purge)

Restoration: any admin calls POST /workspaces/{ws_id}/restore within the grace period
- status returns to active, deleted_at is cleared, all member access is restored

Automatic purge: daily background job deletes workspaces where status = ''pending_deletion'' AND deleted_at < NOW() - INTERVAL ''30 days''. This is a hard CASCADE DELETE — all nodes, edges, members, invites, and chat sessions are deleted. Cannot be undone.

Grace period by KB type:
- evergreen: 30 days
- ephemeral: 7 days

Schema change:
ALTER TABLE workspaces ADD COLUMN status TEXT NOT NULL DEFAULT ''active'' CHECK (status IN (''active'',''pending_deletion'',''deleted'')), ADD COLUMN deleted_at TIMESTAMPTZ;',ARRAY['workspace', 'lifecycle', 'soft-delete', 'grace-period', 'deletion', 'restore']::text[],'public',
   'system','2026-04-12T00:00:00Z','e2f3a4b5c6d7e2f3a4b5c6d7e2f3a4b5c6d7e2f3a4b5c6d7e2f3a4b5c6d7e2f3','human',
   0.95,0.95,1.0,0.9,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_o001','1.0','ws_spec0001','初次使用引導：Web UI 精靈','First-run onboarding: web UI wizard','procedural','plain',
   '首次登入後自動顯示，完成後永久不再彈出（可從 Settings → Getting Started 重新開啟）。八步流程：

① 建立帳號（Email + Password）
② 驗證 Email
③ 命名第一個知識庫（雙語名稱 + 可見性，預設 private）
④ 選擇知識庫類型：Evergreen（長效型，預設）或 Ephemeral（短效型）— **建立後不可變更**
⑤ 選擇起點：空白 或 上傳文件（.md/.txt/.pdf/.docx）
⑥ AI Provider 設定（僅文件路徑顯示，可跳過）
⑦ Review 萃取候選節點（至少接受一個才能繼續）
⑧ 完成（顯示三個捷徑：手動新增節點、邀請成員、連接 AI 工具）

進度以伺服器端的 `onboarding` 物件追蹤（`steps_done[]` + `steps_skipped[]`），中斷後可從上次未完成步驟恢復。`completed: true` 後永遠不再自動顯示。','Shown automatically on first login; permanently dismissed after completion (re-accessible from Settings → Getting Started). Eight-step flow:

① Create account (Email + Password)
② Verify email
③ Name first Knowledge Base (bilingual name + visibility, default private)
④ Choose Knowledge Base Type: Evergreen (default) or Ephemeral — **immutable after creation**
⑤ Choose starting point: blank or upload document (.md/.txt/.pdf/.docx)
⑥ AI provider setup (shown only on document path, skippable)
⑦ Review extracted candidate nodes (at least one must be accepted to advance)
⑧ Done (three shortcuts: add first node, invite someone, connect AI tool)

Progress tracked server-side via the `onboarding` object (`steps_done[]` + `steps_skipped[]`); resumes from the last incomplete step after interruption. Once `completed: true`, the wizard is never shown automatically again.',ARRAY['onboarding', 'ui', 'wizard', 'ux', 'kb-type']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8','human',
   0.95,0.95,1.0,0.9,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_o002','1.0','ws_spec0001','初次使用引導：CLI memtrace init','First-run onboarding: CLI memtrace init','procedural','plain',
   '執行 `memtrace init` 啟動終端機互動式精靈，五步：

① 認證：登入既有帳號 / 建立新帳號
② 建立第一個知識庫：英文名稱 + 可見性（private / restricted / public，預設 private）
③ 選擇 KB 類型：evergreen（長效型，預設）或 ephemeral（短效型）— **建立後不可變更**
④ AI Provider 設定（可 Enter 跳過）：選擇 openai / anthropic 並輸入 API Key（自動測試連線）
⑤ 匯入文件（可 Enter 跳過）：輸入檔案路徑或 URL

設定寫入 `~/.memtrace/config.json`，立即 `chmod 600`。

重複執行：詢問要更新 AI provider / 切換預設工作區 / 重新認證 / 退出，不自動覆寫現有設定。','Running `memtrace init` launches an interactive terminal wizard with five steps:

① Authentication: log in to existing account / create new account
② Create first Knowledge Base: English name + visibility (private / restricted / public, default private)
③ Choose KB type: evergreen (default) or ephemeral — **immutable after creation**
④ AI provider setup (press Enter to skip): choose openai / anthropic and enter API key (auto-tests connection)
⑤ Import document (press Enter to skip): provide file path or URL

Config written to `~/.memtrace/config.json` with `chmod 600` immediately.

Re-running: prompts which setting to update — AI provider / switch default workspace / re-authenticate / exit. Existing values are not overwritten unless explicitly selected.',ARRAY['onboarding', 'cli', 'init', 'setup', 'kb-type']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9a4b5c6d7e8f9','human',
   0.95,0.95,1.0,0.9,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_p001','1.0','ws_spec0001','知識透過連結而非積累','Knowledge through connection, not accumulation','context','plain',
   'MemTrace 的核心前提：知識不需要存在於龐大的文件中。每個節點只捕捉一個想法，價值來自節點之間的連結網絡。節點本身輕量，但透過關聯性形成龐大的知識庫。知識庫的規模不是由單一節點的大小決定，而是由節點之間關係的密度與品質決定。','The core premise of MemTrace: knowledge does not need to live in large, monolithic documents. Each node captures one idea. Value emerges from the network of relationships between nodes. A node alone is lightweight; connected to others, it becomes part of a knowledge base whose scale is determined by the density and quality of its relationships, not the size of any single entry.',ARRAY['philosophy', 'core', 'design-principle']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_p002','1.0','ws_spec0001','為知識傳承而設計','Designed for knowledge inheritance','context','plain',
   'MemTrace 為「非作者」設計。無論是剛加入的團隊成員、中途加入的協作者，還是在陌生情境中運作的 AI agent，都能從任何節點進入知識庫，沿著 Edge 找到所有相關內容，不需要原作者引導。每個節點設計上要自給自足到可以獨立閱讀，同時又透過 Edge 連結讓讀者可以自然深入探索。','MemTrace is designed for the reader who was not there when the knowledge was created. A new team member, a late collaborator, or an AI agent in an unfamiliar context — all can enter at any node and navigate by following edges, without needing the original author to guide them. Each node is self-contained enough to read in isolation, yet connected enough that following its edges leads naturally to everything related.',ARRAY['philosophy', 'core', 'design-principle', 'inheritance']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3','human',
   0.95,0.95,1.0,0.95,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_p003','1.0','ws_spec0001','人與 AI 的協作知識圖','Co-authorship between humans and AI','context','plain',
   'MemTrace 中，人與 AI 寫入同一張圖。圖的結構——Edge 的權重、走訪計數、評分——反映哪些知識實際上被證明有用，而非只是被記錄。Decay 確保圖的誠實性：沒人走的連結自然消退，頻繁被使用的連結強化並持續存在。最終形成一個圍繞「真正重要的知識」自我組織的知識庫。','In MemTrace, humans and AI write into the same graph. The graph''s structure — edge weights, traversal counts, path ratings — reflects which knowledge has actually proven useful, not just what was recorded. Decay keeps the graph honest: connections nobody follows fade; connections visited frequently, rated positively, or extended by other nodes strengthen and persist. The result is a knowledge base that self-organises around what actually matters.',ARRAY['philosophy', 'core', 'ai', 'co-authorship']::text[],'public',
   'memtrace-spec','2026-04-11T00:00:00Z','c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4','human',
   0.95,0.95,1.0,0.9,0.9,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_w001','1.0','ws_spec0001','專案套件結構','Project Package Structure','factual','markdown',
   'MemTrace 採用 npm workspaces monorepo，根目錄 `package.json` 管理四個套件：

| 套件 | 路徑 | 語言 | 角色 |
|------|------|------|------|
| core | packages/core | TypeScript | 共用型別、decay 計算、ID/簽章產生器 |
| api | packages/api | Python/FastAPI | REST API、資料庫存取、OAuth |
| ui | packages/ui | React/Vite | 網頁前端 |
| cli | packages/cli | TypeScript | 本地 CLI 工具 |

`core` 由 `cli` 引用；`api` 獨立於 TS 套件之外。','MemTrace uses an npm workspaces monorepo. The root `package.json` manages four packages:

| Package | Path | Language | Role |
|---------|------|----------|------|
| core | packages/core | TypeScript | Shared types, decay logic, ID/signature generator |
| api | packages/api | Python/FastAPI | REST API, database access, OAuth |
| ui | packages/ui | React/Vite | Web frontend |
| cli | packages/cli | TypeScript | Local CLI tool |

`core` is consumed by `cli`. `api` is independent of the TS workspace.',ARRAY['dev', 'architecture', 'monorepo']::text[],'public',
   'usr_system01','2025-01-01T00:00:00Z','','human',
   0.8,0.8,1.0,0.8,0.8,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_w002','1.0','ws_spec0001','本地開發環境啟動','Local Development Stack Setup','procedural','markdown',
   '## 前置需求
- Node.js 20+
- Python **3.9+**（注意：MCP SDK 需要 3.10+，但 MemTrace API 本身 3.9 可執行）
- PostgreSQL 17（含 pgvector extension）

## 資料庫初始化
```bash
psql -U postgres -c "CREATE DATABASE memtrace;"
psql -U postgres -d memtrace -f schema/sql/001_init.sql
```

## 環境變數（**repo 根目錄** `.env`）
```
DATABASE_URL=postgresql://memtrace:password@127.0.0.1:5432/memtrace
SECRET_KEY=<random-32-chars>
```

## 啟動服務
```bash
# 安裝 TS 相依性（含 MCP 套件）
npm install

# 安裝 Python 相依性
cd packages/api && pip install -r requirements.txt

# 終端機 1：FastAPI（含 decay 排程器）
cd packages/api && uvicorn main:app --reload --port 8000

# 終端機 2：Vite 前端（proxy 預設指向 localhost:8000）
cd packages/ui && npm run dev

# MCP server（供 Claude Code 使用）
# 透過 .mcp.json 自動啟動，或手動：
node packages/mcp/dist/index.js
```

## Docker（一鍵啟動 DB）
```bash
docker compose up -d   # 啟動 PostgreSQL
```','## Prerequisites
- Node.js 20+
- Python **3.9+** (note: MCP SDK requires 3.10+, but MemTrace API itself runs on 3.9)
- PostgreSQL 17 (with pgvector extension)

## Database Init
```bash
psql -U postgres -c "CREATE DATABASE memtrace;"
psql -U postgres -d memtrace -f schema/sql/001_init.sql
```

## Environment Variables (**repo root** `.env`)
```
DATABASE_URL=postgresql://memtrace:password@127.0.0.1:5432/memtrace
SECRET_KEY=<random-32-chars>
```

## Start Services
```bash
# Install TS dependencies (includes MCP package)
npm install

# Install Python dependencies
cd packages/api && pip install -r requirements.txt

# Terminal 1: FastAPI (includes decay scheduler)
cd packages/api && uvicorn main:app --reload --port 8000

# Terminal 2: Vite frontend (proxy pre-configured to localhost:8000)
cd packages/ui && npm run dev

# MCP server (used by Claude Code)
# Auto-started via .mcp.json, or manually:
node packages/mcp/dist/index.js
```

## Docker (one-command DB)
```bash
docker compose up -d   # starts PostgreSQL
```',ARRAY['dev', 'setup', 'database', 'procedural']::text[],'public',
   'system','2025-01-01T00:00:00Z','','human',
   0.8,0.8,1.0,0.8,0.8,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_w003','1.0','ws_spec0001','Seed 載入 Spec KB','Seeding the Spec Knowledge Base','procedural','markdown',
   '## 執行 Seed
```bash
cd D:/Workspace/MemTrace/packages/api
python ../../scripts/seed_spec_kb.py
```

Script 會自動偵測 `system@memtrace.local` 的系統使用者 ID（目前為 `system`），建立工作區 `ws_spec0001`，並以 upsert（ON CONFLICT DO UPDATE）寫入所有節點與邊。

## 驗證
```bash
curl http://localhost:8000/api/v1/workspaces/ws_spec0001/nodes | jq length
# 期望：27
```

## 注意事項
- `.env` 位於 **repo 根目錄**（非 `packages/api/`）
- 需在 `packages/api` venv 下執行，確保 psycopg2 可用
- 重複執行安全：upsert 不會重複建立，但會以 JSON 內容覆寫現有節點','## Run Seed
```bash
cd D:/Workspace/MemTrace/packages/api
python ../../scripts/seed_spec_kb.py
```

The script auto-detects the system user ID for `system@memtrace.local` (currently `system`), creates workspace `ws_spec0001`, and upserts all nodes and edges (ON CONFLICT DO UPDATE).

## Verify
```bash
curl http://localhost:8000/api/v1/workspaces/ws_spec0001/nodes | jq length
# Expected: 27
```

## Notes
- `.env` lives in the **repo root** (not `packages/api/`)
- Run inside the `packages/api` venv so psycopg2 is available
- Safe to re-run: upsert won''t duplicate, but will overwrite existing node content with JSON',ARRAY['dev', 'seed', 'procedural']::text[],'public',
   'system','2025-01-01T00:00:00Z','','human',
   0.8,0.8,1.0,0.8,0.8,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;

INSERT INTO memory_nodes
  (id,schema_version,workspace_id,title_zh,title_en,content_type,content_format,
   body_zh,body_en,tags,visibility,author,created_at,signature,source_type,
   trust_score,dim_accuracy,dim_freshness,dim_utility,dim_author_rep,
   votes_up,votes_down,verifications,traversal_count,unique_traverser_count)
VALUES
  ('mem_w004','1.0','ws_spec0001','開發實作順序','Development Implementation Order','procedural','markdown',
   'MemTrace 建議開發順序（由底層向上）：

1. **core** — 核心型別、decay、ID/簽章
2. **SQL schema** — 001_init.sql，建立資料表
3. **api/core** — config、database、security、deps
4. **api/routers/auth** — register、login、JWT
5. **api/routers/kb** — workspace、node、edge CRUD + traversal
6. **cli** — init、new、link、list、export、import、copy-node
7. **Seed** — 匯入 spec-as-kb 以驗證 API 讀寫（`scripts/seed_spec_kb.py`）
8. **ui/api.ts** — TypeScript API client
9. **ui/AuthPage** — 登入 / 註冊
10. **ui/NodeEditor** — 節點編輯器（含 edge panel、節點搜尋）
11. **ui/GraphView** — 2D 關係圖，雙擊開啟 NodeEditor
12. **ui/App** — 串接 auth、workspace selector、側邊欄
13. **MCP server** — `packages/mcp/`，目前實作 4 個唯讀工具（search_nodes、get_node、traverse、list_by_tag），透過 `.mcp.json` 註冊給 Claude Code

**當前進度：1–13 步已完成（MCP 唯讀端點）**

**後續優先事項**：
- 權限模型（viewer / contributor / admin 角色實作、contributor 提案流程）
- 工作區軟刪除（status 欄位、30 天清理排程）
- 對話式問答 API（`/chat` endpoint + chat_sessions / chat_messages 資料表）
- AI 匯入流程（`routers/ai.py` 實作）
- Copy Node API
- 語意搜尋端點
- 工作區邀請連結 API','Recommended build order for MemTrace (bottom-up):

1. **core** — types, decay, ID/signature
2. **SQL schema** — 001_init.sql, create all tables
3. **api/core** — config, database, security, deps
4. **api/routers/auth** — register, login, JWT
5. **api/routers/kb** — workspace, node, edge CRUD + traversal
6. **cli** — init, new, link, list, export, import, copy-node
7. **Seed** — load spec-as-kb to validate API reads/writes (`scripts/seed_spec_kb.py`)
8. **ui/api.ts** — TypeScript API client
9. **ui/AuthPage** — login / register
10. **ui/NodeEditor** — node editor with edge panel and node search
11. **ui/GraphView** — 2D graph, double-click to open NodeEditor
12. **ui/App** — wire auth, workspace selector, side panel
13. **MCP server** — `packages/mcp/`, currently implements 4 read-only tools (search_nodes, get_node, traverse, list_by_tag); registered to Claude Code via `.mcp.json`

**Current status: phases 1–13 complete (MCP read-only)**

**Next priorities**:
- Permission model (viewer / contributor / admin role enforcement, contributor proposal flow)
- Workspace soft-delete (status column, 30-day purge scheduler)
- Conversational Q&A API (/chat endpoint + chat_sessions / chat_messages tables)
- AI ingestion pipeline (complete `routers/ai.py`)
- Copy Node API
- Semantic search endpoint
- Workspace invite link API',ARRAY['dev', 'workflow', 'procedural']::text[],'public',
   'system','2025-01-01T00:00:00Z','','human',
   0.8,0.8,1.0,0.8,0.8,
   0,0,0,0,0)
ON CONFLICT (id) DO UPDATE SET
  title_zh=EXCLUDED.title_zh, title_en=EXCLUDED.title_en,
  body_zh=EXCLUDED.body_zh, body_en=EXCLUDED.body_en,
  tags=EXCLUDED.tags, trust_score=EXCLUDED.trust_score,
  dim_accuracy=EXCLUDED.dim_accuracy, dim_freshness=EXCLUDED.dim_freshness,
  dim_utility=EXCLUDED.dim_utility, dim_author_rep=EXCLUDED.dim_author_rep;


-- Edges
INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_p001_d001','ws_spec0001','mem_p001','mem_d001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_p001_d002','ws_spec0001','mem_p001','mem_d002','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_p002_d006','ws_spec0001','mem_p002','mem_d006','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_p002_d005','ws_spec0001','mem_p002','mem_d005','related_to',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_p003_i003','ws_spec0001','mem_p003','mem_i003','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_p003_g001','ws_spec0001','mem_p003','mem_g001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_p001_p002','ws_spec0001','mem_p001','mem_p002','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_p001_p003','ws_spec0001','mem_p001','mem_p003','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_d001_d003','ws_spec0001','mem_d001','mem_d003','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_d001_d004','ws_spec0001','mem_d001','mem_d004','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_d001_d005','ws_spec0001','mem_d001','mem_d005','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_d001_d006','ws_spec0001','mem_d001','mem_d006','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_d002_g003','ws_spec0001','mem_d002','mem_g003','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_d002_g001','ws_spec0001','mem_d002','mem_g001','related_to',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_d005_i001','ws_spec0001','mem_d005','mem_i001','related_to',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_d006_g002','ws_spec0001','mem_d006','mem_g002','related_to',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_g001_d002','ws_spec0001','mem_g001','mem_d002','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_g002_g001','ws_spec0001','mem_g002','mem_g001','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_g002_g003','ws_spec0001','mem_g002','mem_g003','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_d004_d001','ws_spec0001','mem_d004','mem_d001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_k001_d001','ws_spec0001','mem_k001','mem_d001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_k001_d002','ws_spec0001','mem_k001','mem_d002','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_k002_k001','ws_spec0001','mem_k002','mem_k001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_k003_k001','ws_spec0001','mem_k003','mem_k001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_k003_d005','ws_spec0001','mem_k003','mem_d005','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_a002_a001','ws_spec0001','mem_a002','mem_a001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_a002_k001','ws_spec0001','mem_a002','mem_k001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_a003_a002','ws_spec0001','mem_a003','mem_a002','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_a003_d001','ws_spec0001','mem_a003','mem_d001','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_i002_i001','ws_spec0001','mem_i002','mem_i001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_i002_k001','ws_spec0001','mem_i002','mem_k001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_i003_i002','ws_spec0001','mem_i003','mem_i002','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_i003_g002','ws_spec0001','mem_i003','mem_g002','related_to',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_o001_i001','ws_spec0001','mem_o001','mem_i001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_o001_k001','ws_spec0001','mem_o001','mem_k001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_o001_a002','ws_spec0001','mem_o001','mem_a002','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_o002_i001','ws_spec0001','mem_o002','mem_i001','depends_on',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_o002_a001','ws_spec0001','mem_o002','mem_a001','extends',1.0,90,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_w001_w002','ws_spec0001','mem_w001','mem_w002','depends_on',1.0,180,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_w002_w003','ws_spec0001','mem_w002','mem_w003','depends_on',1.0,180,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_w004_w001','ws_spec0001','mem_w004','mem_w001','depends_on',1.0,180,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_w004_d001','ws_spec0001','mem_w004','mem_d001','related_to',1.0,180,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_w004_i001','ws_spec0001','mem_w004','mem_i001','related_to',1.0,180,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_w002_d006','ws_spec0001','mem_w002','mem_d006','related_to',1.0,180,0.1,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_i004_i001','ws_spec0001','mem_i004','mem_i001','extends',1.0,180,0.05,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_i004_i002','ws_spec0001','mem_i004','mem_i002','extends',1.0,180,0.05,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_i004_i003','ws_spec0001','mem_i004','mem_i003','related_to',1.0,180,0.05,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_i004_a003','ws_spec0001','mem_i004','mem_a003','related_to',1.0,180,0.05,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_k004_k001','ws_spec0001','mem_k004','mem_k001','extends',1.0,180,0.05,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_k004_i004','ws_spec0001','mem_k004','mem_i004','depends_on',1.0,180,0.05,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_k004_g003','ws_spec0001','mem_k004','mem_g003','related_to',1.0,180,0.05,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_a004_a001','ws_spec0001','mem_a004','mem_a001','depends_on',1.0,180,0.05,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_a004_i004','ws_spec0001','mem_a004','mem_i004','depends_on',1.0,180,0.05,false,0,0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO edges (id,workspace_id,from_id,to_id,relation,weight,half_life_days,min_weight,pinned,co_access_count,traversal_count)
VALUES ('edge_a004_i003','ws_spec0001','mem_a004','mem_i003','related_to',1.0,180,0.05,false,0,0)
ON CONFLICT (id) DO NOTHING;
